/**
 * Generates teamInfos.ts from teamDataInput.ts
 * Run: npx tsx tools/generateTeamInfos.ts
 */

import { teams } from "./teamDataInput";
import { writeFileSync } from "fs";
import { join } from "path";

// Conference ID mapping
const conferenceIds: Record<string, number> = {
	"Atlantic 10": 0,
	"ACC": 1,
	"Big Ten": 2,
	"Big 12": 3,
	"SEC": 4,
	"Big East": 5,
	"West Coast": 6,
	"American": 7,
	"Missouri Valley": 8,
	"Mountain West": 9,
	"Conference USA": 10,
	"Colonial": 11,
	"Horizon": 12,
	"Ivy League": 13,
	"MAAC": 14,
	"MAC": 15,
	"MEAC": 16,
	"NEC": 17,
	"Ohio Valley": 18,
	"Patriot": 19,
	"Southern": 20,
	"Southland": 21,
	"SWAC": 22,
	"Summit": 23,
	"Sun Belt": 24,
	"WAC": 25,
	"Big Sky": 26,
	"Big South": 27,
	"Big West": 28,
	"America East": 29,
	"ASUN": 30,
};

// Group teams by conference
const teamsByConference: Record<string, typeof teams> = {};
for (const team of teams) {
	if (!teamsByConference[team.conference]) {
		teamsByConference[team.conference] = [];
	}
	teamsByConference[team.conference].push(team);
}

// Generate TypeScript code
let code = `// Generated by tools/generateTeamInfos.ts
// DO NOT EDIT MANUALLY - Edit tools/teamDataInput.ts instead

import bySport from "./bySport";

const teamInfos: {
\t[key: string]: {
\t\tregion: string;
\t\tname: string;
\t\tpop: number;
\t\tstate?: string;
\t\tprestigeBase?: number;
\t\tcolors: [string, string, string];
\t\tjersey: string;
\t};
} = {\n`;

let tid = 0;
const conferences = Object.keys(conferenceIds).sort((a, b) => conferenceIds[a] - conferenceIds[b]);
const usedAbbrevs = new Set<string>();

for (const conferenceName of conferences) {
	const confTeams = teamsByConference[conferenceName];
	if (!confTeams || confTeams.length === 0) continue;

	const cid = conferenceIds[conferenceName];
	code += `\t// ${conferenceName} (${confTeams.length} teams)\n`;

	for (const team of confTeams) {
		let abbrev = generateAbbrev(team.city, team.mascot);

		// Handle abbreviation collisions
		let counter = 1;
		const baseAbbrev = abbrev;
		while (usedAbbrevs.has(abbrev)) {
			// Try adding state code or counter
			if (counter === 1) {
				abbrev = team.state.substring(0, 2).toUpperCase() + baseAbbrev.substring(2, 3);
			} else {
				abbrev = baseAbbrev.substring(0, 2) + counter;
			}
			counter++;
		}
		usedAbbrevs.add(abbrev);

		// Ensure all teams have 3 colors
		const colors = team.colors.length === 3 ? team.colors : [...team.colors, "#FFFFFF"];

		code += `\t${abbrev}: {\n`;
		code += `\t\tregion: "${team.city}",\n`;
		code += `\t\tname: "${team.mascot}",\n`;
		code += `\t\tpop: 1,\n`;
		code += `\t\tstate: "${team.state}",\n`;
		code += `\t\tprestigeBase: ${team.prestigeBase},\n`;
		code += `\t\tcolors: ${JSON.stringify(colors)},\n`;
		code += `\t\tjersey: bySport({\n`;
		code += `\t\t\tbaseball: "baseball2:hat2",\n`;
		code += `\t\t\tbasketball: "jersey3",\n`;
		code += `\t\t\tfootball: "football2",\n`;
		code += `\t\t\thockey: "hockey3",\n`;
		code += `\t\t}),\n`;
		code += `\t},\n`;

		tid++;
	}
}

code += `};\n\nexport default teamInfos;\n`;

// Write to file
const outputPath = join(process.cwd(), "src", "common", "teamInfos.ts");
writeFileSync(outputPath, code, "utf-8");

console.log(`✅ Generated teamInfos.ts with ${tid} teams`);
console.log(`   Conferences: ${conferences.length}`);
console.log(`   Output: ${outputPath}`);

// Helper function to generate 3-letter abbreviations
function generateAbbrev(city: string, mascot: string): string {
	// Try city first
	const cityWords = city.split(" ");
	if (cityWords.length === 1) {
		return city.substring(0, 3).toUpperCase();
	}

	// Multiple words - use first letters
	if (cityWords.length >= 3) {
		return (cityWords[0][0] + cityWords[1][0] + cityWords[2][0]).toUpperCase();
	}

	// Two words
	return (cityWords[0][0] + cityWords[1].substring(0, 2)).toUpperCase();
}
