/**
 * NCAA Team Data Input
 * Format: Add teams with all their details, then run generateTeamInfos.ts to create teamInfos.ts
 */

export interface TeamInput {
	fullName: string; // Original school name (for reference)
	city: string; // City for variant name
	mascot: string;
	state: string; // 2-letter code
	conference: string;
	colors: string[]; // Hex codes (primary, secondary, accent)
	prestigeBase: number; // 0-100 rating
}

export const teams: TeamInput[] = [
	// Atlantic 10 (14 teams)
	{ fullName: "Davidson College", city: "Davidson", mascot: "Wildcats", state: "NC", conference: "Atlantic 10", colors: ["#CE1126", "#000000"], prestigeBase: 58 },
	{ fullName: "University of Dayton", city: "Dayton", mascot: "Flyers", state: "OH", conference: "Atlantic 10", colors: ["#CE1126", "#003A70"], prestigeBase: 62 },
	{ fullName: "Duquesne University", city: "Pittsburgh", mascot: "Dukes", state: "PA", conference: "Atlantic 10", colors: ["#003087", "#BA0C2F"], prestigeBase: 55 },
	{ fullName: "Fordham University", city: "Bronx", mascot: "Rams", state: "NY", conference: "Atlantic 10", colors: ["#862633", "#000000"], prestigeBase: 48 },
	{ fullName: "George Mason University", city: "Fairfax", mascot: "Patriots", state: "VA", conference: "Atlantic 10", colors: ["#006633", "#FFCC33"], prestigeBase: 56 },
	{ fullName: "George Washington University", city: "Washington", mascot: "Revolutionaries", state: "DC", conference: "Atlantic 10", colors: ["#033C5A", "#AA9868"], prestigeBase: 52 },
	{ fullName: "La Salle University", city: "Philadelphia", mascot: "Explorers", state: "PA", conference: "Atlantic 10", colors: ["#041E42", "#C5B783"], prestigeBase: 50 },
	{ fullName: "Loyola University Chicago", city: "Chicago", mascot: "Ramblers", state: "IL", conference: "Atlantic 10", colors: ["#8D2B3C", "#EFB81C"], prestigeBase: 60 },
	{ fullName: "University of Rhode Island", city: "Kingston", mascot: "Rams", state: "RI", conference: "Atlantic 10", colors: ["#002147", "#75B2DD"], prestigeBase: 54 },
	{ fullName: "University of Richmond", city: "Richmond", mascot: "Spiders", state: "VA", conference: "Atlantic 10", colors: ["#002F87", "#C8102E"], prestigeBase: 58 },
	{ fullName: "St. Bonaventure University", city: "Olean", mascot: "Bonnies", state: "NY", conference: "Atlantic 10", colors: ["#66330C", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Saint Joseph's University", city: "Philadelphia", mascot: "Hawks", state: "PA", conference: "Atlantic 10", colors: ["#660018", "#999999"], prestigeBase: 59 },
	{ fullName: "Saint Louis University", city: "St. Louis", mascot: "Billikens", state: "MO", conference: "Atlantic 10", colors: ["#005DAA", "#FFFFFF"], prestigeBase: 62 },
	{ fullName: "Virginia Commonwealth University", city: "Richmond", mascot: "Rams", state: "VA", conference: "Atlantic 10", colors: ["#000000", "#F8B800"], prestigeBase: 65 },

	// ACC (17 teams)
	{ fullName: "Boston College", city: "Chestnut Hill", mascot: "Eagles", state: "MA", conference: "ACC", colors: ["#98002E", "#C4A43A", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "University of California, Berkeley", city: "Berkeley", mascot: "Golden Bears", state: "CA", conference: "ACC", colors: ["#003262", "#FDB515", "#FFFFFF"], prestigeBase: 66 },
	{ fullName: "Clemson University", city: "Clemson", mascot: "Tigers", state: "SC", conference: "ACC", colors: ["#F66733", "#522D80", "#FFFFFF"], prestigeBase: 71 },
	{ fullName: "Duke University", city: "Durham", mascot: "Blue Devils", state: "NC", conference: "ACC", colors: ["#00539B", "#FFFFFF", "#012169"], prestigeBase: 98 },
	{ fullName: "Florida State University", city: "Tallahassee", mascot: "Seminoles", state: "FL", conference: "ACC", colors: ["#782F40", "#CEB888", "#000000"], prestigeBase: 74 },
	{ fullName: "Georgia Institute of Technology", city: "Atlanta", mascot: "Yellow Jackets", state: "GA", conference: "ACC", colors: ["#B3A369", "#003057", "#FFFFFF"], prestigeBase: 67 },
	{ fullName: "University of Louisville", city: "Louisville", mascot: "Cardinals", state: "KY", conference: "ACC", colors: ["#AD0000", "#000000", "#FFFFFF"], prestigeBase: 82 },
	{ fullName: "University of Miami", city: "Coral Gables", mascot: "Hurricanes", state: "FL", conference: "ACC", colors: ["#F47321", "#005030", "#FFFFFF"], prestigeBase: 69 },
	{ fullName: "University of North Carolina at Chapel Hill", city: "Chapel Hill", mascot: "Tar Heels", state: "NC", conference: "ACC", colors: ["#7BAFD4", "#FFFFFF", "#13294B"], prestigeBase: 97 },
	{ fullName: "North Carolina State University", city: "Raleigh", mascot: "Wolfpack", state: "NC", conference: "ACC", colors: ["#CC0000", "#FFFFFF", "#000000"], prestigeBase: 72 },
	{ fullName: "University of Notre Dame", city: "South Bend", mascot: "Fighting Irish", state: "IN", conference: "ACC", colors: ["#0C2340", "#C99700", "#FFFFFF"], prestigeBase: 75 },
	{ fullName: "University of Pittsburgh", city: "Pittsburgh", mascot: "Panthers", state: "PA", conference: "ACC", colors: ["#003594", "#FFB81C", "#FFFFFF"], prestigeBase: 73 },
	{ fullName: "Southern Methodist University", city: "Dallas", mascot: "Mustangs", state: "TX", conference: "ACC", colors: ["#C8102E", "#003A63", "#FFFFFF"], prestigeBase: 65 },
	{ fullName: "Stanford University", city: "Stanford", mascot: "Cardinal", state: "CA", conference: "ACC", colors: ["#8C1515", "#FFFFFF", "#000000"], prestigeBase: 70 },
	{ fullName: "Syracuse University", city: "Syracuse", mascot: "Orange", state: "NY", conference: "ACC", colors: ["#F76900", "#FFFFFF", "#000E54"], prestigeBase: 77 },
	{ fullName: "University of Virginia", city: "Charlottesville", mascot: "Cavaliers", state: "VA", conference: "ACC", colors: ["#232D4B", "#F84C1E", "#FFFFFF"], prestigeBase: 78 },
	{ fullName: "Virginia Polytechnic Institute and State University", city: "Blacksburg", mascot: "Hokies", state: "VA", conference: "ACC", colors: ["#630031", "#CF4420", "#FFFFFF"], prestigeBase: 70 },
	{ fullName: "Wake Forest University", city: "Winston-Salem", mascot: "Demon Deacons", state: "NC", conference: "ACC", colors: ["#000000", "#CFB87C", "#FFFFFF"], prestigeBase: 70 },

	// Big Ten (18 teams)
	{ fullName: "University of California, Los Angeles", city: "Westwood", mascot: "Bruins", state: "CA", conference: "Big Ten", colors: ["#2D68C4", "#FFD100", "#FFFFFF"], prestigeBase: 95 },
	{ fullName: "University of Illinois Urbana–Champaign", city: "Champaign", mascot: "Fighting Illini", state: "IL", conference: "Big Ten", colors: ["#13294B", "#E84A27", "#FFFFFF"], prestigeBase: 75 },
	{ fullName: "Indiana University Bloomington", city: "Bloomington", mascot: "Hoosiers", state: "IN", conference: "Big Ten", colors: ["#990000", "#FFFFFF", "#000000"], prestigeBase: 85 },
	{ fullName: "University of Iowa", city: "Iowa City", mascot: "Hawkeyes", state: "IA", conference: "Big Ten", colors: ["#000000", "#FFCD00", "#FFFFFF"], prestigeBase: 69 },
	{ fullName: "University of Maryland, College Park", city: "College Park", mascot: "Terrapins", state: "MD", conference: "Big Ten", colors: ["#E03A3E", "#FFD520", "#000000"], prestigeBase: 76 },
	{ fullName: "University of Michigan", city: "Ann Arbor", mascot: "Wolverines", state: "MI", conference: "Big Ten", colors: ["#00274C", "#FFCB05", "#FFFFFF"], prestigeBase: 80 },
	{ fullName: "Michigan State University", city: "East Lansing", mascot: "Spartans", state: "MI", conference: "Big Ten", colors: ["#18453B", "#FFFFFF", "#000000"], prestigeBase: 82 },
	{ fullName: "University of Minnesota", city: "Minneapolis", mascot: "Golden Gophers", state: "MN", conference: "Big Ten", colors: ["#7A0019", "#FFCC33", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "University of Nebraska–Lincoln", city: "Lincoln", mascot: "Cornhuskers", state: "NE", conference: "Big Ten", colors: ["#E41C38", "#FFFFFF", "#000000"], prestigeBase: 64 },
	{ fullName: "Northwestern University", city: "Evanston", mascot: "Wildcats", state: "IL", conference: "Big Ten", colors: ["#4E2A84", "#FFFFFF", "#000000"], prestigeBase: 66 },
	{ fullName: "Ohio State University", city: "Columbus", mascot: "Buckeyes", state: "OH", conference: "Big Ten", colors: ["#BB0000", "#666666", "#FFFFFF"], prestigeBase: 74 },
	{ fullName: "University of Oregon", city: "Eugene", mascot: "Ducks", state: "OR", conference: "Big Ten", colors: ["#154733", "#FEE123", "#FFFFFF"], prestigeBase: 73 },
	{ fullName: "Pennsylvania State University", city: "State College", mascot: "Nittany Lions", state: "PA", conference: "Big Ten", colors: ["#041E42", "#FFFFFF", "#000000"], prestigeBase: 70 },
	{ fullName: "Purdue University", city: "West Lafayette", mascot: "Boilermakers", state: "IN", conference: "Big Ten", colors: ["#000000", "#CFB991", "#FFFFFF"], prestigeBase: 76 },
	{ fullName: "Rutgers University–New Brunswick", city: "Piscataway", mascot: "Scarlet Knights", state: "NJ", conference: "Big Ten", colors: ["#CC0033", "#000000", "#FFFFFF"], prestigeBase: 65 },
	{ fullName: "University of Southern California", city: "Los Angeles", mascot: "Trojans", state: "CA", conference: "Big Ten", colors: ["#990000", "#FFC72C", "#FFFFFF"], prestigeBase: 72 },
	{ fullName: "University of Washington", city: "Seattle", mascot: "Huskies", state: "WA", conference: "Big Ten", colors: ["#4B2E83", "#B7A57A", "#FFFFFF"], prestigeBase: 72 },
	{ fullName: "University of Wisconsin–Madison", city: "Madison", mascot: "Badgers", state: "WI", conference: "Big Ten", colors: ["#C5050C", "#FFFFFF", "#000000"], prestigeBase: 78 },

	// Big 12 (16 teams)
	{ fullName: "University of Arizona", city: "Tucson", mascot: "Wildcats", state: "AZ", conference: "Big 12", colors: ["#003366", "#CC0033", "#FFFFFF"], prestigeBase: 77 },
	{ fullName: "Arizona State University", city: "Tempe", mascot: "Sun Devils", state: "AZ", conference: "Big 12", colors: ["#8C1D40", "#FFC627", "#000000"], prestigeBase: 69 },
	{ fullName: "Baylor University", city: "Waco", mascot: "Bears", state: "TX", conference: "Big 12", colors: ["#003015", "#FECB00", "#FFFFFF"], prestigeBase: 70 },
	{ fullName: "Brigham Young University", city: "Provo", mascot: "Cougars", state: "UT", conference: "Big 12", colors: ["#002E5D", "#FFFFFF", "#000000"], prestigeBase: 65 },
	{ fullName: "University of Central Florida", city: "Orlando", mascot: "Knights", state: "FL", conference: "Big 12", colors: ["#000000", "#B4975A", "#FFFFFF"], prestigeBase: 66 },
	{ fullName: "University of Cincinnati", city: "Cincinnati", mascot: "Bearcats", state: "OH", conference: "Big 12", colors: ["#E00122", "#000000", "#FFFFFF"], prestigeBase: 74 },
	{ fullName: "University of Colorado Boulder", city: "Boulder", mascot: "Buffaloes", state: "CO", conference: "Big 12", colors: ["#CFB87C", "#000000", "#FFFFFF"], prestigeBase: 67 },
	{ fullName: "University of Houston", city: "Houston", mascot: "Cougars", state: "TX", conference: "Big 12", colors: ["#C8102E", "#FFFFFF", "#000000"], prestigeBase: 72 },
	{ fullName: "Iowa State University", city: "Ames", mascot: "Cyclones", state: "IA", conference: "Big 12", colors: ["#C8102E", "#F1BE48", "#000000"], prestigeBase: 66 },
	{ fullName: "University of Kansas", city: "Lawrence", mascot: "Jayhawks", state: "KS", conference: "Big 12", colors: ["#0051BA", "#E8000D", "#FFFFFF"], prestigeBase: 96 },
	{ fullName: "Kansas State University", city: "Manhattan", mascot: "Wildcats", state: "KS", conference: "Big 12", colors: ["#512888", "#FFFFFF", "#000000"], prestigeBase: 67 },
	{ fullName: "Oklahoma State University–Stillwater", city: "Stillwater", mascot: "Cowboys", state: "OK", conference: "Big 12", colors: ["#FF6600", "#000000", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "Texas Christian University", city: "Fort Worth", mascot: "Horned Frogs", state: "TX", conference: "Big 12", colors: ["#4D1979", "#A3A9AC", "#FFFFFF"], prestigeBase: 69 },
	{ fullName: "Texas Tech University", city: "Lubbock", mascot: "Red Raiders", state: "TX", conference: "Big 12", colors: ["#CC0000", "#000000", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "University of Utah", city: "Salt Lake City", mascot: "Utes", state: "UT", conference: "Big 12", colors: ["#CC0000", "#000000", "#FFFFFF"], prestigeBase: 66 },
	{ fullName: "West Virginia University", city: "Morgantown", mascot: "Mountaineers", state: "WV", conference: "Big 12", colors: ["#002855", "#EAAA00", "#FFFFFF"], prestigeBase: 70 },

	// SEC (16 teams)
	{ fullName: "University of Alabama", city: "Tuscaloosa", mascot: "Crimson Tide", state: "AL", conference: "SEC", colors: ["#9E1B32", "#FFFFFF", "#828A8F"], prestigeBase: 68 },
	{ fullName: "University of Arkansas", city: "Fayetteville", mascot: "Razorbacks", state: "AR", conference: "SEC", colors: ["#9D2235", "#FFFFFF", "#000000"], prestigeBase: 72 },
	{ fullName: "Auburn University", city: "Auburn", mascot: "Tigers", state: "AL", conference: "SEC", colors: ["#0C2340", "#E87722", "#FFFFFF"], prestigeBase: 71 },
	{ fullName: "University of Florida", city: "Gainesville", mascot: "Gators", state: "FL", conference: "SEC", colors: ["#0021A5", "#FA4616", "#FFFFFF"], prestigeBase: 76 },
	{ fullName: "University of Georgia", city: "Athens", mascot: "Bulldogs", state: "GA", conference: "SEC", colors: ["#BA0C2F", "#000000", "#FFFFFF"], prestigeBase: 70 },
	{ fullName: "University of Kentucky", city: "Lexington", mascot: "Wildcats", state: "KY", conference: "SEC", colors: ["#0033A0", "#FFFFFF", "#000000"], prestigeBase: 98 },
	{ fullName: "Louisiana State University", city: "Baton Rouge", mascot: "Tigers", state: "LA", conference: "SEC", colors: ["#461D7C", "#FDD023", "#FFFFFF"], prestigeBase: 73 },
	{ fullName: "University of Mississippi", city: "Oxford", mascot: "Rebels", state: "MS", conference: "SEC", colors: ["#CE1126", "#14213D", "#FFFFFF"], prestigeBase: 69 },
	{ fullName: "Mississippi State University", city: "Starkville", mascot: "Bulldogs", state: "MS", conference: "SEC", colors: ["#660000", "#FFFFFF", "#000000"], prestigeBase: 66 },
	{ fullName: "University of Missouri", city: "Columbia", mascot: "Tigers", state: "MO", conference: "SEC", colors: ["#F1B82D", "#000000", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "University of Oklahoma", city: "Norman", mascot: "Sooners", state: "OK", conference: "SEC", colors: ["#841617", "#FDF9D8", "#000000"], prestigeBase: 71 },
	{ fullName: "University of South Carolina", city: "Columbia", mascot: "Gamecocks", state: "SC", conference: "SEC", colors: ["#73000A", "#000000", "#FFFFFF"], prestigeBase: 67 },
	{ fullName: "University of Tennessee", city: "Knoxville", mascot: "Volunteers", state: "TN", conference: "SEC", colors: ["#FF8200", "#FFFFFF", "#000000"], prestigeBase: 70 },
	{ fullName: "University of Texas at Austin", city: "Austin", mascot: "Longhorns", state: "TX", conference: "SEC", colors: ["#BF5700", "#FFFFFF", "#000000"], prestigeBase: 73 },
	{ fullName: "Texas A&M University", city: "College Station", mascot: "Aggies", state: "TX", conference: "SEC", colors: ["#500000", "#FFFFFF", "#000000"], prestigeBase: 69 },
	{ fullName: "Vanderbilt University", city: "Nashville", mascot: "Commodores", state: "TN", conference: "SEC", colors: ["#866D4B", "#000000", "#FFFFFF"], prestigeBase: 67 },

	// Big East (11 teams)
	{ fullName: "Butler University", city: "Indianapolis", mascot: "Bulldogs", state: "IN", conference: "Big East", colors: ["#13294B", "#FFFFFF", "#000000"], prestigeBase: 70 },
	{ fullName: "Creighton University", city: "Omaha", mascot: "Bluejays", state: "NE", conference: "Big East", colors: ["#00539F", "#FFFFFF", "#000000"], prestigeBase: 72 },
	{ fullName: "DePaul University", city: "Chicago", mascot: "Blue Demons", state: "IL", conference: "Big East", colors: ["#1D428A", "#C8102E", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "Georgetown University", city: "Washington", mascot: "Hoyas", state: "DC", conference: "Big East", colors: ["#041E42", "#8D817B", "#FFFFFF"], prestigeBase: 76 },
	{ fullName: "Marquette University", city: "Milwaukee", mascot: "Golden Eagles", state: "WI", conference: "Big East", colors: ["#003865", "#EEB211", "#FFFFFF"], prestigeBase: 73 },
	{ fullName: "Providence College", city: "Providence", mascot: "Friars", state: "RI", conference: "Big East", colors: ["#000000", "#FFFFFF", "#000000"], prestigeBase: 71 },
	{ fullName: "St. John's University", city: "Queens", mascot: "Red Storm", state: "NY", conference: "Big East", colors: ["#EE2737", "#FFFFFF", "#000000"], prestigeBase: 72 },
	{ fullName: "Seton Hall University", city: "Newark", mascot: "Pirates", state: "NJ", conference: "Big East", colors: ["#005DAA", "#FFFFFF", "#000000"], prestigeBase: 69 },
	{ fullName: "University of Connecticut", city: "Storrs", mascot: "Huskies", state: "CT", conference: "Big East", colors: ["#000E2F", "#FFFFFF", "#E4002B"], prestigeBase: 83 },
	{ fullName: "Villanova University", city: "Villanova", mascot: "Wildcats", state: "PA", conference: "Big East", colors: ["#00205B", "#FFFFFF", "#00205B"], prestigeBase: 85 },
	{ fullName: "Xavier University", city: "Cincinnati", mascot: "Musketeers", state: "OH", conference: "Big East", colors: ["#13294B", "#FFFFFF", "#000000"], prestigeBase: 74 },

	// West Coast Conference (12 teams)
	{ fullName: "Gonzaga University", city: "Spokane", mascot: "Bulldogs", state: "WA", conference: "West Coast", colors: ["#041E42", "#C8102E", "#FFFFFF"], prestigeBase: 82 },
	{ fullName: "Loyola Marymount University", city: "Los Angeles", mascot: "Lions", state: "CA", conference: "West Coast", colors: ["#8D0335", "#104E8B", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Oregon State University", city: "Corvallis", mascot: "Beavers", state: "OR", conference: "West Coast", colors: ["#DC4405", "#000000", "#FFFFFF"], prestigeBase: 64 },
	{ fullName: "University of the Pacific", city: "Stockton", mascot: "Tigers", state: "CA", conference: "West Coast", colors: ["#FF6600", "#000000", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Pepperdine University", city: "Malibu", mascot: "Waves", state: "CA", conference: "West Coast", colors: ["#003262", "#FF6A39", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of Portland", city: "Portland", mascot: "Pilots", state: "OR", conference: "West Coast", colors: ["#512888", "#FFFFFF", "#000000"], prestigeBase: 62 },
	{ fullName: "Saint Mary's College of California", city: "Moraga", mascot: "Gaels", state: "CA", conference: "West Coast", colors: ["#003DA5", "#C4122E", "#FFFFFF"], prestigeBase: 68 },
	{ fullName: "University of San Diego", city: "San Diego", mascot: "Toreros", state: "CA", conference: "West Coast", colors: ["#005CB9", "#78BE21", "#FFFFFF"], prestigeBase: 62 },
	{ fullName: "University of San Francisco", city: "San Francisco", mascot: "Dons", state: "CA", conference: "West Coast", colors: ["#FDBB30", "#00543C", "#FFFFFF"], prestigeBase: 66 },
	{ fullName: "Santa Clara University", city: "Santa Clara", mascot: "Broncos", state: "CA", conference: "West Coast", colors: ["#B30838", "#5B6770", "#FFFFFF"], prestigeBase: 64 },
	{ fullName: "Seattle University", city: "Seattle", mascot: "Redhawks", state: "WA", conference: "West Coast", colors: ["#AA0000", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Washington State University", city: "Pullman", mascot: "Cougars", state: "WA", conference: "West Coast", colors: ["#981E32", "#5E6A71", "#FFFFFF"], prestigeBase: 65 },

	// American Athletic Conference (13 teams)
	{ fullName: "University of North Carolina at Charlotte", city: "Charlotte", mascot: "49ers", state: "NC", conference: "American", colors: ["#005035", "#B9975B", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "East Carolina University", city: "Greenville", mascot: "Pirates", state: "NC", conference: "American", colors: ["#592A8A", "#FFC600", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Florida Atlantic University", city: "Boca Raton", mascot: "Owls", state: "FL", conference: "American", colors: ["#003366", "#CC0000", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "University of Memphis", city: "Memphis", mascot: "Tigers", state: "TN", conference: "American", colors: ["#00285E", "#8D9093", "#FFFFFF"], prestigeBase: 70 },
	{ fullName: "University of North Texas", city: "Denton", mascot: "Mean Green", state: "TX", conference: "American", colors: ["#00853E", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "Rice University", city: "Houston", mascot: "Owls", state: "TX", conference: "American", colors: ["#00205B", "#8D9093", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "University of South Florida", city: "Tampa", mascot: "Bulls", state: "FL", conference: "American", colors: ["#006747", "#CFC493", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Temple University", city: "Philadelphia", mascot: "Owls", state: "PA", conference: "American", colors: ["#9B1C1C", "#FFFFFF", "#000000"], prestigeBase: 61 },
	{ fullName: "University of Alabama at Birmingham", city: "Birmingham", mascot: "Blazers", state: "AL", conference: "American", colors: ["#1E6B52", "#FFB81C", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "University of Texas at San Antonio", city: "San Antonio", mascot: "Roadrunners", state: "TX", conference: "American", colors: ["#0C2340", "#F15A22", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Tulane University", city: "New Orleans", mascot: "Green Wave", state: "LA", conference: "American", colors: ["#006747", "#7BAFD4", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of Tulsa", city: "Tulsa", mascot: "Golden Hurricane", state: "OK", conference: "American", colors: ["#002D72", "#C5B783", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Wichita State University", city: "Wichita", mascot: "Shockers", state: "KS", conference: "American", colors: ["#000000", "#FFCD00", "#FFFFFF"], prestigeBase: 64 },

	// Missouri Valley Conference (11 teams)
	{ fullName: "Belmont University", city: "Nashville", mascot: "Bruins", state: "TN", conference: "Missouri Valley", colors: ["#000E2F", "#AD0035", "#FFFFFF"], prestigeBase: 62 },
	{ fullName: "Bradley University", city: "Peoria", mascot: "Braves", state: "IL", conference: "Missouri Valley", colors: ["#D22730", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Drake University", city: "Des Moines", mascot: "Bulldogs", state: "IA", conference: "Missouri Valley", colors: ["#005AA9", "#FFFFFF", "#000000"], prestigeBase: 59 },
	{ fullName: "University of Evansville", city: "Evansville", mascot: "Purple Aces", state: "IN", conference: "Missouri Valley", colors: ["#522D80", "#E87722", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Illinois State University", city: "Normal", mascot: "Redbirds", state: "IL", conference: "Missouri Valley", colors: ["#CE1126", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Indiana State University", city: "Terre Haute", mascot: "Sycamores", state: "IN", conference: "Missouri Valley", colors: ["#004C97", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Murray State University", city: "Murray", mascot: "Racers", state: "KY", conference: "Missouri Valley", colors: ["#003B7B", "#FFC72C", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of Northern Iowa", city: "Cedar Falls", mascot: "Panthers", state: "IA", conference: "Missouri Valley", colors: ["#4B116F", "#FFB300", "#FFFFFF"], prestigeBase: 61 },
	{ fullName: "Southern Illinois University Carbondale", city: "Carbondale", mascot: "Salukis", state: "IL", conference: "Missouri Valley", colors: ["#660000", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "University of Illinois Chicago", city: "Chicago", mascot: "Flames", state: "IL", conference: "Missouri Valley", colors: ["#001E62", "#D50032", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Valparaiso University", city: "Valparaiso", mascot: "Beacons", state: "IN", conference: "Missouri Valley", colors: ["#5D3A1A", "#F2A900", "#FFFFFF"], prestigeBase: 57 },

	// Mountain West Conference (11 teams)
	{ fullName: "United States Air Force Academy", city: "Colorado Springs", mascot: "Falcons", state: "CO", conference: "Mountain West", colors: ["#003087", "#8A8D8F", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Boise State University", city: "Boise", mascot: "Broncos", state: "ID", conference: "Mountain West", colors: ["#0033A0", "#D64309", "#FFFFFF"], prestigeBase: 61 },
	{ fullName: "Colorado State University", city: "Fort Collins", mascot: "Rams", state: "CO", conference: "Mountain West", colors: ["#1E4D2B", "#C8C372", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "California State University, Fresno", city: "Fresno", mascot: "Bulldogs", state: "CA", conference: "Mountain West", colors: ["#DB0032", "#003A70", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "University of Nevada, Reno", city: "Reno", mascot: "Wolf Pack", state: "NV", conference: "Mountain West", colors: ["#003366", "#C0C0C0", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of New Mexico", city: "Albuquerque", mascot: "Lobos", state: "NM", conference: "Mountain West", colors: ["#BA0C2F", "#63666A", "#FFFFFF"], prestigeBase: 62 },
	{ fullName: "San Diego State University", city: "San Diego", mascot: "Aztecs", state: "CA", conference: "Mountain West", colors: ["#000000", "#A6192E", "#FFFFFF"], prestigeBase: 67 },
	{ fullName: "San Jose State University", city: "San Jose", mascot: "Spartans", state: "CA", conference: "Mountain West", colors: ["#0055A2", "#E5A823", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "University of Nevada, Las Vegas", city: "Las Vegas", mascot: "Runnin' Rebels", state: "NV", conference: "Mountain West", colors: ["#B10202", "#696969", "#FFFFFF"], prestigeBase: 65 },
	{ fullName: "Utah State University", city: "Logan", mascot: "Aggies", state: "UT", conference: "Mountain West", colors: ["#003057", "#8B8B8B", "#FFFFFF"], prestigeBase: 63 },
	{ fullName: "University of Wyoming", city: "Laramie", mascot: "Cowboys", state: "WY", conference: "Mountain West", colors: ["#492F24", "#FFC425", "#FFFFFF"], prestigeBase: 57 },

	// Conference USA (12 teams)
	{ fullName: "University of Delaware", city: "Newark", mascot: "Fightin' Blue Hens", state: "DE", conference: "Conference USA", colors: ["#00539F", "#FFD200", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Florida International University", city: "Miami", mascot: "Panthers", state: "FL", conference: "Conference USA", colors: ["#081E3F", "#B6862C", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Jacksonville State University", city: "Jacksonville", mascot: "Gamecocks", state: "AL", conference: "Conference USA", colors: ["#CC0033", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "Kennesaw State University", city: "Kennesaw", mascot: "Owls", state: "GA", conference: "Conference USA", colors: ["#000000", "#FDB913", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Liberty University", city: "Lynchburg", mascot: "Flames", state: "VA", conference: "Conference USA", colors: ["#002147", "#A50034", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Louisiana Tech University", city: "Ruston", mascot: "Bulldogs", state: "LA", conference: "Conference USA", colors: ["#002F8B", "#E31B23", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Middle Tennessee State University", city: "Murfreesboro", mascot: "Blue Raiders", state: "TN", conference: "Conference USA", colors: ["#0066CC", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Missouri State University", city: "Springfield", mascot: "Bears", state: "MO", conference: "Conference USA", colors: ["#5E0000", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "New Mexico State University", city: "Las Cruces", mascot: "Aggies", state: "NM", conference: "Conference USA", colors: ["#8B0015", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Sam Houston State University", city: "Huntsville", mascot: "Bearkats", state: "TX", conference: "Conference USA", colors: ["#F47321", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "University of Texas at El Paso", city: "El Paso", mascot: "Miners", state: "TX", conference: "Conference USA", colors: ["#FF8200", "#041E42", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Western Kentucky University", city: "Bowling Green", mascot: "Hilltoppers", state: "KY", conference: "Conference USA", colors: ["#C4122E", "#FFFFFF", "#000000"], prestigeBase: 61 },

	// Colonial Athletic Association (13 teams)
	{ fullName: "Campbell University", city: "Buies Creek", mascot: "Fighting Camels", state: "NC", conference: "Colonial", colors: ["#F47920", "#000000", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "College of Charleston", city: "Charleston", mascot: "Cougars", state: "SC", conference: "Colonial", colors: ["#84212E", "#FFFFFF", "#000000"], prestigeBase: 61 },
	{ fullName: "Drexel University", city: "Philadelphia", mascot: "Dragons", state: "PA", conference: "Colonial", colors: ["#002F6C", "#FFC600", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "Elon University", city: "Elon", mascot: "Phoenix", state: "NC", conference: "Colonial", colors: ["#73000A", "#9E7E38", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Hampton University", city: "Hampton", mascot: "Pirates", state: "VA", conference: "Colonial", colors: ["#0067B9", "#FFFFFF", "#000000"], prestigeBase: 52 },
	{ fullName: "Hofstra University", city: "Hempstead", mascot: "Pride", state: "NY", conference: "Colonial", colors: ["#005DAA", "#FDBB30", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Monmouth University", city: "West Long Branch", mascot: "Hawks", state: "NJ", conference: "Colonial", colors: ["#005EB8", "#012169", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "North Carolina Agricultural and Technical State University", city: "Greensboro", mascot: "Aggies", state: "NC", conference: "Colonial", colors: ["#00539B", "#EEB211", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Northeastern University", city: "Boston", mascot: "Huskies", state: "MA", conference: "Colonial", colors: ["#CC0000", "#000000", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "Stony Brook University", city: "Stony Brook", mascot: "Seawolves", state: "NY", conference: "Colonial", colors: ["#990000", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Towson University", city: "Towson", mascot: "Tigers", state: "MD", conference: "Colonial", colors: ["#FFCC00", "#000000", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "University of North Carolina at Wilmington", city: "Wilmington", mascot: "Seahawks", state: "NC", conference: "Colonial", colors: ["#006272", "#FFC845", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "College of William & Mary", city: "Williamsburg", mascot: "Tribe", state: "VA", conference: "Colonial", colors: ["#115740", "#B9975B", "#FFFFFF"], prestigeBase: 55 },

	// Horizon League (11 teams)
	{ fullName: "Cleveland State University", city: "Cleveland", mascot: "Vikings", state: "OH", conference: "Horizon", colors: ["#005C2E", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "University of Detroit Mercy", city: "Detroit", mascot: "Titans", state: "MI", conference: "Horizon", colors: ["#C3151C", "#033D6A", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Indiana University Indianapolis", city: "Indianapolis", mascot: "Jaguars", state: "IN", conference: "Horizon", colors: ["#990000", "#FFFFFF", "#000000"], prestigeBase: 52 },
	{ fullName: "University of Wisconsin-Milwaukee", city: "Milwaukee", mascot: "Panthers", state: "WI", conference: "Horizon", colors: ["#000000", "#FFAA00", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Northern Kentucky University", city: "Highland Heights", mascot: "Norse", state: "KY", conference: "Horizon", colors: ["#000000", "#FFC72C", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Oakland University", city: "Rochester", mascot: "Golden Grizzlies", state: "MI", conference: "Horizon", colors: ["#CCAD00", "#000000", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "Purdue University Fort Wayne", city: "Fort Wayne", mascot: "Mastodons", state: "IN", conference: "Horizon", colors: ["#000000", "#8D6A3C", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Robert Morris University", city: "Moon Township", mascot: "Colonials", state: "PA", conference: "Horizon", colors: ["#013A81", "#C41E3A", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "University of Wisconsin–Green Bay", city: "Green Bay", mascot: "Phoenix", state: "WI", conference: "Horizon", colors: ["#004F3F", "#E41C38", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Wright State University", city: "Dayton", mascot: "Raiders", state: "OH", conference: "Horizon", colors: ["#005A43", "#FFB500", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Youngstown State University", city: "Youngstown", mascot: "Penguins", state: "OH", conference: "Horizon", colors: ["#C8102E", "#FFFFFF", "#000000"], prestigeBase: 54 },

	// Ivy League (8 teams)
	{ fullName: "Brown University", city: "Providence", mascot: "Bears", state: "RI", conference: "Ivy League", colors: ["#4E3629", "#E83E2A", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Columbia University", city: "New York", mascot: "Lions", state: "NY", conference: "Ivy League", colors: ["#C4D8E2", "#003DA5", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Cornell University", city: "Ithaca", mascot: "Big Red", state: "NY", conference: "Ivy League", colors: ["#B31B1B", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "Dartmouth College", city: "Hanover", mascot: "Big Green", state: "NH", conference: "Ivy League", colors: ["#00693E", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "Harvard University", city: "Cambridge", mascot: "Crimson", state: "MA", conference: "Ivy League", colors: ["#A41034", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "University of Pennsylvania", city: "Philadelphia", mascot: "Quakers", state: "PA", conference: "Ivy League", colors: ["#011F5B", "#990000", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Princeton University", city: "Princeton", mascot: "Tigers", state: "NJ", conference: "Ivy League", colors: ["#FF8F00", "#000000", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Yale University", city: "New Haven", mascot: "Bulldogs", state: "CT", conference: "Ivy League", colors: ["#00356B", "#FFFFFF", "#000000"], prestigeBase: 59 },

	// Mid-American Conference (13 teams)
	{ fullName: "University of Akron", city: "Akron", mascot: "Zips", state: "OH", conference: "MAC", colors: ["#003D79", "#A89968", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Ball State University", city: "Muncie", mascot: "Cardinals", state: "IN", conference: "MAC", colors: ["#BA0C2F", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Bowling Green State University", city: "Bowling Green", mascot: "Falcons", state: "OH", conference: "MAC", colors: ["#FE5000", "#4F2A1D", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "University at Buffalo", city: "Buffalo", mascot: "Bulls", state: "NY", conference: "MAC", colors: ["#005BBB", "#FFFFFF", "#000000"], prestigeBase: 60 },
	{ fullName: "Central Michigan University", city: "Mount Pleasant", mascot: "Chippewas", state: "MI", conference: "MAC", colors: ["#6A0032", "#FFC72C", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Eastern Michigan University", city: "Ypsilanti", mascot: "Eagles", state: "MI", conference: "MAC", colors: ["#006633", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "Kent State University", city: "Kent", mascot: "Golden Flashes", state: "OH", conference: "MAC", colors: ["#002664", "#E5A823", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "University of Massachusetts Amherst", city: "Amherst", mascot: "Minutemen", state: "MA", conference: "MAC", colors: ["#881C1C", "#FFFFFF", "#000000"], prestigeBase: 62 },
	{ fullName: "Miami University", city: "Oxford", mascot: "RedHawks", state: "OH", conference: "MAC", colors: ["#C41E3A", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Northern Illinois University", city: "DeKalb", mascot: "Huskies", state: "IL", conference: "MAC", colors: ["#BA0C2F", "#000000", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Ohio University", city: "Athens", mascot: "Bobcats", state: "OH", conference: "MAC", colors: ["#00694E", "#FFFFFF", "#000000"], prestigeBase: 61 },
	{ fullName: "University of Toledo", city: "Toledo", mascot: "Rockets", state: "OH", conference: "MAC", colors: ["#003E7E", "#FFC72C", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Western Michigan University", city: "Kalamazoo", mascot: "Broncos", state: "MI", conference: "MAC", colors: ["#672F1F", "#EBC23C", "#FFFFFF"], prestigeBase: 57 },

	// Metro Atlantic Athletic Conference (13 teams)
	{ fullName: "Canisius University", city: "Buffalo", mascot: "Golden Griffins", state: "NY", conference: "MAAC", colors: ["#003E7E", "#FDB927", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Fairfield University", city: "Fairfield", mascot: "Stags", state: "CT", conference: "MAAC", colors: ["#BC0000", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Iona University", city: "New Rochelle", mascot: "Gaels", state: "NY", conference: "MAAC", colors: ["#822433", "#FFD100", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Manhattan University", city: "Bronx", mascot: "Jaspers", state: "NY", conference: "MAAC", colors: ["#005030", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "Marist College", city: "Poughkeepsie", mascot: "Red Foxes", state: "NY", conference: "MAAC", colors: ["#C8102E", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Merrimack College", city: "North Andover", mascot: "Warriors", state: "MA", conference: "MAAC", colors: ["#003865", "#FFC72C", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Mount St. Mary's University", city: "Emmitsburg", mascot: "Mountaineers", state: "MD", conference: "MAAC", colors: ["#003B7A", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "Niagara University", city: "Lewiston", mascot: "Purple Eagles", state: "NY", conference: "MAAC", colors: ["#582C83", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Quinnipiac University", city: "Hamden", mascot: "Bobcats", state: "CT", conference: "MAAC", colors: ["#003E7E", "#FFC72C", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "Rider University", city: "Lawrenceville", mascot: "Broncs", state: "NJ", conference: "MAAC", colors: ["#8E2C48", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Sacred Heart University", city: "Fairfield", mascot: "Pioneers", state: "CT", conference: "MAAC", colors: ["#CE1126", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Saint Peter's University", city: "Jersey City", mascot: "Peacocks", state: "NJ", conference: "MAAC", colors: ["#006DAA", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Siena College", city: "Loudonville", mascot: "Saints", state: "NY", conference: "MAAC", colors: ["#006B3F", "#E8AC1C", "#FFFFFF"], prestigeBase: 59 },

	// MEAC (8 teams)
	{ fullName: "Coppin State University", city: "Baltimore", mascot: "Eagles", state: "MD", conference: "MEAC", colors: ["#003087", "#FDB913", "#FFFFFF"], prestigeBase: 48 },
	{ fullName: "Delaware State University", city: "Dover", mascot: "Hornets", state: "DE", conference: "MEAC", colors: ["#CC0000", "#003E7E", "#FFFFFF"], prestigeBase: 49 },
	{ fullName: "Howard University", city: "Washington", mascot: "Bison", state: "DC", conference: "MEAC", colors: ["#003A63", "#E51937", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "University of Maryland Eastern Shore", city: "Princess Anne", mascot: "Hawks", state: "MD", conference: "MEAC", colors: ["#8B0015", "#FFD100", "#FFFFFF"], prestigeBase: 47 },
	{ fullName: "Morgan State University", city: "Baltimore", mascot: "Bears", state: "MD", conference: "MEAC", colors: ["#F47920", "#003E7E", "#FFFFFF"], prestigeBase: 50 },
	{ fullName: "Norfolk State University", city: "Norfolk", mascot: "Spartans", state: "VA", conference: "MEAC", colors: ["#007A33", "#FFCD00", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "North Carolina Central University", city: "Durham", mascot: "Eagles", state: "NC", conference: "MEAC", colors: ["#73000A", "#CCCCCC", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "South Carolina State University", city: "Orangeburg", mascot: "Bulldogs", state: "SC", conference: "MEAC", colors: ["#862633", "#003DA5", "#FFFFFF"], prestigeBase: 50 },

	// Ohio Valley Conference (11 teams)
	{ fullName: "Eastern Illinois University", city: "Charleston", mascot: "Panthers", state: "IL", conference: "Ohio Valley", colors: ["#004B83", "#B9975B", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Lindenwood University", city: "St. Charles", mascot: "Lions", state: "MO", conference: "Ohio Valley", colors: ["#000000", "#CFB87C", "#FFFFFF"], prestigeBase: 50 },
	{ fullName: "University of Arkansas at Little Rock", city: "Little Rock", mascot: "Trojans", state: "AR", conference: "Ohio Valley", colors: ["#8B0015", "#7C878E", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Morehead State University", city: "Morehead", mascot: "Eagles", state: "KY", conference: "Ohio Valley", colors: ["#003087", "#FFC72C", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Southeast Missouri State University", city: "Cape Girardeau", mascot: "Redhawks", state: "MO", conference: "Ohio Valley", colors: ["#C8102E", "#000000", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Southern Illinois University Edwardsville", city: "Edwardsville", mascot: "Cougars", state: "IL", conference: "Ohio Valley", colors: ["#CE1126", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "University of Southern Indiana", city: "Evansville", mascot: "Screaming Eagles", state: "IN", conference: "Ohio Valley", colors: ["#C8102E", "#002D62", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "University of Tennessee at Martin", city: "Martin", mascot: "Skyhawks", state: "TN", conference: "Ohio Valley", colors: ["#FF8200", "#003087", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Tennessee State University", city: "Nashville", mascot: "Tigers", state: "TN", conference: "Ohio Valley", colors: ["#003087", "#7F9EB2", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Tennessee Tech University", city: "Cookeville", mascot: "Golden Eagles", state: "TN", conference: "Ohio Valley", colors: ["#4F2682", "#FFC72C", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Western Illinois University", city: "Macomb", mascot: "Leathernecks", state: "IL", conference: "Ohio Valley", colors: ["#4B116F", "#FFAA00", "#FFFFFF"], prestigeBase: 52 },

	// Patriot League (10 teams)
	{ fullName: "American University", city: "Washington", mascot: "Eagles", state: "DC", conference: "Patriot", colors: ["#C41E3A", "#003566", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "United States Military Academy", city: "West Point", mascot: "Black Knights", state: "NY", conference: "Patriot", colors: ["#000000", "#B1A374", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "Boston University", city: "Boston", mascot: "Terriers", state: "MA", conference: "Patriot", colors: ["#CC0000", "#FFFFFF", "#000000"], prestigeBase: 60 },
	{ fullName: "Bucknell University", city: "Lewisburg", mascot: "Bison", state: "PA", conference: "Patriot", colors: ["#003478", "#EF7D00", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Colgate University", city: "Hamilton", mascot: "Raiders", state: "NY", conference: "Patriot", colors: ["#821019", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "College of the Holy Cross", city: "Worcester", mascot: "Crusaders", state: "MA", conference: "Patriot", colors: ["#602D89", "#FFFFFF", "#000000"], prestigeBase: 59 },
	{ fullName: "Lafayette College", city: "Easton", mascot: "Leopards", state: "PA", conference: "Patriot", colors: ["#8B0015", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Lehigh University", city: "Bethlehem", mascot: "Mountain Hawks", state: "PA", conference: "Patriot", colors: ["#653612", "#FFFFFF", "#000000"], prestigeBase: 59 },
	{ fullName: "Loyola University Maryland", city: "Baltimore", mascot: "Greyhounds", state: "MD", conference: "Patriot", colors: ["#00703C", "#8A8B8C", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "United States Naval Academy", city: "Annapolis", mascot: "Midshipmen", state: "MD", conference: "Patriot", colors: ["#003E7E", "#C5B358", "#FFFFFF"], prestigeBase: 56 },

	// Southern Conference (10 teams)
	{ fullName: "University of Tennessee at Chattanooga", city: "Chattanooga", mascot: "Mocs", state: "TN", conference: "Southern", colors: ["#00386B", "#F0AB00", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "The Citadel", city: "Charleston", mascot: "Bulldogs", state: "SC", conference: "Southern", colors: ["#003A70", "#B5B5B3", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "East Tennessee State University", city: "Johnson City", mascot: "Buccaneers", state: "TN", conference: "Southern", colors: ["#003F87", "#FFC72C", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Furman University", city: "Greenville", mascot: "Paladins", state: "SC", conference: "Southern", colors: ["#582C83", "#FFFFFF", "#000000"], prestigeBase: 62 },
	{ fullName: "Mercer University", city: "Macon", mascot: "Bears", state: "GA", conference: "Southern", colors: ["#FF8200", "#000000", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "Samford University", city: "Birmingham", mascot: "Bulldogs", state: "AL", conference: "Southern", colors: ["#003087", "#C41E3A", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of North Carolina at Greensboro", city: "Greensboro", mascot: "Spartans", state: "NC", conference: "Southern", colors: ["#FFCC00", "#041E42", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Virginia Military Institute", city: "Lexington", mascot: "Keydets", state: "VA", conference: "Southern", colors: ["#C8102E", "#FFD100", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Western Carolina University", city: "Cullowhee", mascot: "Catamounts", state: "NC", conference: "Southern", colors: ["#592C82", "#C5B358", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Wofford College", city: "Spartanburg", mascot: "Terriers", state: "SC", conference: "Southern", colors: ["#CFAB7A", "#000000", "#FFFFFF"], prestigeBase: 61 },

	// Southland Conference (12 teams)
	{ fullName: "East Texas A&M University", city: "Commerce", mascot: "Lions", state: "TX", conference: "Southland", colors: ["#003087", "#FFC72C", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Houston Christian University", city: "Houston", mascot: "Huskies", state: "TX", conference: "Southland", colors: ["#CC0000", "#C4D600", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "University of the Incarnate Word", city: "San Antonio", mascot: "Cardinals", state: "TX", conference: "Southland", colors: ["#C8102E", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "Lamar University", city: "Beaumont", mascot: "Cardinals", state: "TX", conference: "Southland", colors: ["#CC0000", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "McNeese State University", city: "Lake Charles", mascot: "Cowboys", state: "LA", conference: "Southland", colors: ["#003087", "#FFC72C", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "University of New Orleans", city: "New Orleans", mascot: "Privateers", state: "LA", conference: "Southland", colors: ["#003087", "#8C8B89", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Nicholls State University", city: "Thibodaux", mascot: "Colonels", state: "LA", conference: "Southland", colors: ["#CC0000", "#CCCCCC", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Northwestern State University", city: "Natchitoches", mascot: "Demons", state: "LA", conference: "Southland", colors: ["#582C83", "#FF8200", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Southeastern Louisiana University", city: "Hammond", mascot: "Lions", state: "LA", conference: "Southland", colors: ["#046A38", "#CFAB7A", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Stephen F. Austin State University", city: "Nacogdoches", mascot: "Lumberjacks", state: "TX", conference: "Southland", colors: ["#582C83", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "Texas A&M University-Corpus Christi", city: "Corpus Christi", mascot: "Islanders", state: "TX", conference: "Southland", colors: ["#003087", "#007F3D", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "University of Texas Rio Grande Valley", city: "Edinburg", mascot: "Vaqueros", state: "TX", conference: "Southland", colors: ["#FF6A13", "#003087", "#FFFFFF"], prestigeBase: 52 },

	// Summit League (9 teams)
	{ fullName: "University of Denver", city: "Denver", mascot: "Pioneers", state: "CO", conference: "Summit", colors: ["#8B2332", "#CFB87C", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "University of Missouri–Kansas City", city: "Kansas City", mascot: "Roos", state: "MO", conference: "Summit", colors: ["#003087", "#FFCD00", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "University of North Dakota", city: "Grand Forks", mascot: "Fighting Hawks", state: "ND", conference: "Summit", colors: ["#006747", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "North Dakota State University", city: "Fargo", mascot: "Bison", state: "ND", conference: "Summit", colors: ["#0A5640", "#FFC72C", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "University of Nebraska Omaha", city: "Omaha", mascot: "Mavericks", state: "NE", conference: "Summit", colors: ["#BA0C2F", "#000000", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Oral Roberts University", city: "Tulsa", mascot: "Golden Eagles", state: "OK", conference: "Summit", colors: ["#002D72", "#C5B358", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of St. Thomas", city: "St. Paul", mascot: "Tommies", state: "MN", conference: "Summit", colors: ["#582C83", "#808080", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "University of South Dakota", city: "Vermillion", mascot: "Coyotes", state: "SD", conference: "Summit", colors: ["#CF0A2C", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "South Dakota State University", city: "Brookings", mascot: "Jackrabbits", state: "SD", conference: "Summit", colors: ["#003466", "#FFC72C", "#FFFFFF"], prestigeBase: 59 },

	// Sun Belt Conference (14 teams)
	{ fullName: "Appalachian State University", city: "Boone", mascot: "Mountaineers", state: "NC", conference: "Sun Belt", colors: ["#000000", "#FFC72C", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Arkansas State University", city: "Jonesboro", mascot: "Red Wolves", state: "AR", conference: "Sun Belt", colors: ["#CC0000", "#000000", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Coastal Carolina University", city: "Conway", mascot: "Chanticleers", state: "SC", conference: "Sun Belt", colors: ["#006F71", "#A57C00", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "Georgia Southern University", city: "Statesboro", mascot: "Eagles", state: "GA", conference: "Sun Belt", colors: ["#003087", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Georgia State University", city: "Atlanta", mascot: "Panthers", state: "GA", conference: "Sun Belt", colors: ["#0039A6", "#C4122E", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "James Madison University", city: "Harrisonburg", mascot: "Dukes", state: "VA", conference: "Sun Belt", colors: ["#450084", "#C5B783", "#FFFFFF"], prestigeBase: 62 },
	{ fullName: "University of Louisiana at Lafayette", city: "Lafayette", mascot: "Ragin' Cajuns", state: "LA", conference: "Sun Belt", colors: ["#CE181E", "#FFFFFF", "#000000"], prestigeBase: 60 },
	{ fullName: "University of Louisiana at Monroe", city: "Monroe", mascot: "Warhawks", state: "LA", conference: "Sun Belt", colors: ["#84202C", "#C99700", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Marshall University", city: "Huntington", mascot: "Thundering Herd", state: "WV", conference: "Sun Belt", colors: ["#00B140", "#000000", "#FFFFFF"], prestigeBase: 61 },
	{ fullName: "Old Dominion University", city: "Norfolk", mascot: "Monarchs", state: "VA", conference: "Sun Belt", colors: ["#003057", "#8C92AC", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "University of South Alabama", city: "Mobile", mascot: "Jaguars", state: "AL", conference: "Sun Belt", colors: ["#00205B", "#C8102E", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "University of Southern Mississippi", city: "Hattiesburg", mascot: "Golden Eagles", state: "MS", conference: "Sun Belt", colors: ["#000000", "#FFAA00", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "Texas State University", city: "San Marcos", mascot: "Bobcats", state: "TX", conference: "Sun Belt", colors: ["#501214", "#B29665", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Troy University", city: "Troy", mascot: "Trojans", state: "AL", conference: "Sun Belt", colors: ["#8C2032", "#8A8D8F", "#FFFFFF"], prestigeBase: 58 },

	// SWAC (12 teams)
	{ fullName: "Alabama Agricultural and Mechanical University", city: "Huntsville", mascot: "Bulldogs", state: "AL", conference: "SWAC", colors: ["#73000A", "#FFAA00", "#FFFFFF"], prestigeBase: 50 },
	{ fullName: "Alabama State University", city: "Montgomery", mascot: "Hornets", state: "AL", conference: "SWAC", colors: ["#000000", "#D4AF37", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Alcorn State University", city: "Lorman", mascot: "Braves", state: "MS", conference: "SWAC", colors: ["#542C84", "#D4AF37", "#FFFFFF"], prestigeBase: 49 },
	{ fullName: "University of Arkansas at Pine Bluff", city: "Pine Bluff", mascot: "Golden Lions", state: "AR", conference: "SWAC", colors: ["#000000", "#D4AF37", "#FFFFFF"], prestigeBase: 48 },
	{ fullName: "Bethune–Cookman University", city: "Daytona Beach", mascot: "Wildcats", state: "FL", conference: "SWAC", colors: ["#73000A", "#D4AF37", "#FFFFFF"], prestigeBase: 50 },
	{ fullName: "Florida Agricultural and Mechanical University", city: "Tallahassee", mascot: "Rattlers", state: "FL", conference: "SWAC", colors: ["#F47920", "#046A38", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Grambling State University", city: "Grambling", mascot: "Tigers", state: "LA", conference: "SWAC", colors: ["#000000", "#D4AF37", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Jackson State University", city: "Jackson", mascot: "Tigers", state: "MS", conference: "SWAC", colors: ["#003F87", "#F58025", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Mississippi Valley State University", city: "Itta Bena", mascot: "Delta Devils", state: "MS", conference: "SWAC", colors: ["#046A38", "#D4AF37", "#FFFFFF"], prestigeBase: 47 },
	{ fullName: "Prairie View A&M University", city: "Prairie View", mascot: "Panthers", state: "TX", conference: "SWAC", colors: ["#582C83", "#D4AF37", "#FFFFFF"], prestigeBase: 50 },
	{ fullName: "Southern University", city: "Baton Rouge", mascot: "Jaguars", state: "LA", conference: "SWAC", colors: ["#003087", "#D4AF37", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Texas Southern University", city: "Houston", mascot: "Tigers", state: "TX", conference: "SWAC", colors: ["#73000A", "#CCCCCC", "#FFFFFF"], prestigeBase: 51 },

	// WAC (7 teams)
	{ fullName: "Abilene Christian University", city: "Abilene", mascot: "Wildcats", state: "TX", conference: "WAC", colors: ["#461D7C", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "California Baptist University", city: "Riverside", mascot: "Lancers", state: "CA", conference: "WAC", colors: ["#003087", "#F15A22", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Southern Utah University", city: "Cedar City", mascot: "Thunderbirds", state: "UT", conference: "WAC", colors: ["#C41E3A", "#003087", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Tarleton State University", city: "Stephenville", mascot: "Texans", state: "TX", conference: "WAC", colors: ["#592C82", "#FFFFFF", "#000000"], prestigeBase: 52 },
	{ fullName: "Utah Tech University", city: "St. George", mascot: "Trailblazers", state: "UT", conference: "WAC", colors: ["#C8102E", "#000000", "#FFFFFF"], prestigeBase: 51 },
	{ fullName: "Utah Valley University", city: "Orem", mascot: "Wolverines", state: "UT", conference: "WAC", colors: ["#165734", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "University of Texas at Arlington", city: "Arlington", mascot: "Mavericks", state: "TX", conference: "WAC", colors: ["#003087", "#F47920", "#FFFFFF"], prestigeBase: 56 },

	// Big Sky Conference (10 teams)
	{ fullName: "Eastern Washington University", city: "Cheney", mascot: "Eagles", state: "WA", conference: "Big Sky", colors: ["#A60F2D", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "University of Idaho", city: "Moscow", mascot: "Vandals", state: "ID", conference: "Big Sky", colors: ["#FFAA00", "#000000", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Idaho State University", city: "Pocatello", mascot: "Bengals", state: "ID", conference: "Big Sky", colors: ["#F56600", "#000000", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "University of Montana", city: "Missoula", mascot: "Grizzlies", state: "MT", conference: "Big Sky", colors: ["#4F0025", "#8D9093", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Montana State University", city: "Bozeman", mascot: "Bobcats", state: "MT", conference: "Big Sky", colors: ["#003366", "#FFC72C", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "Northern Arizona University", city: "Flagstaff", mascot: "Lumberjacks", state: "AZ", conference: "Big Sky", colors: ["#003466", "#FFC627", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "University of Northern Colorado", city: "Greeley", mascot: "Bears", state: "CO", conference: "Big Sky", colors: ["#003466", "#FFC627", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Portland State University", city: "Portland", mascot: "Vikings", state: "OR", conference: "Big Sky", colors: ["#046A38", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "California State University, Sacramento", city: "Sacramento", mascot: "Hornets", state: "CA", conference: "Big Sky", colors: ["#005430", "#C0A875", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Weber State University", city: "Ogden", mascot: "Wildcats", state: "UT", conference: "Big Sky", colors: ["#492F91", "#FFFFFF", "#000000"], prestigeBase: 59 },

	// Big South Conference (9 teams)
	{ fullName: "Charleston Southern University", city: "Charleston", mascot: "Buccaneers", state: "SC", conference: "Big South", colors: ["#003087", "#D4AF37", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Gardner–Webb University", city: "Boiling Springs", mascot: "Runnin' Bulldogs", state: "NC", conference: "Big South", colors: ["#CE1126", "#000000", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "High Point University", city: "High Point", mascot: "Panthers", state: "NC", conference: "Big South", colors: ["#663096", "#FFFFFF", "#000000"], prestigeBase: 58 },
	{ fullName: "Longwood University", city: "Farmville", mascot: "Lancers", state: "VA", conference: "Big South", colors: ["#003087", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "Presbyterian College", city: "Clinton", mascot: "Blue Hose", state: "SC", conference: "Big South", colors: ["#062A78", "#C8102E", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Radford University", city: "Radford", mascot: "Highlanders", state: "VA", conference: "Big South", colors: ["#C8102E", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "University of North Carolina at Asheville", city: "Asheville", mascot: "Bulldogs", state: "NC", conference: "Big South", colors: ["#003F87", "#003F87", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "University of South Carolina Upstate", city: "Spartanburg", mascot: "Spartans", state: "SC", conference: "Big South", colors: ["#005430", "#000000", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Winthrop University", city: "Rock Hill", mascot: "Eagles", state: "SC", conference: "Big South", colors: ["#872434", "#FFC600", "#FFFFFF"], prestigeBase: 60 },

	// Big West Conference (11 teams)
	{ fullName: "California Polytechnic State University", city: "San Luis Obispo", mascot: "Mustangs", state: "CA", conference: "Big West", colors: ["#004F3E", "#C69214", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "California State University, Bakersfield", city: "Bakersfield", mascot: "Roadrunners", state: "CA", conference: "Big West", colors: ["#003F87", "#E57200", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "California State University, Fullerton", city: "Fullerton", mascot: "Titans", state: "CA", conference: "Big West", colors: ["#003263", "#F57E25", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "California State University, Northridge", city: "Northridge", mascot: "Matadors", state: "CA", conference: "Big West", colors: ["#D22730", "#000000", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "University of Hawaiʻi at Mānoa", city: "Honolulu", mascot: "Rainbow Warriors", state: "HI", conference: "Big West", colors: ["#024731", "#FFFFFF", "#000000"], prestigeBase: 59 },
	{ fullName: "California State University, Long Beach", city: "Long Beach", mascot: "The Beach", state: "CA", conference: "Big West", colors: ["#000000", "#F2A900", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "University of California, Davis", city: "Davis", mascot: "Aggies", state: "CA", conference: "Big West", colors: ["#003366", "#FFBF00", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "University of California, Irvine", city: "Irvine", mascot: "Anteaters", state: "CA", conference: "Big West", colors: ["#00549F", "#FFD200", "#FFFFFF"], prestigeBase: 60 },
	{ fullName: "University of California, Riverside", city: "Riverside", mascot: "Highlanders", state: "CA", conference: "Big West", colors: ["#003466", "#FFD100", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "University of California, San Diego", city: "San Diego", mascot: "Tritons", state: "CA", conference: "Big West", colors: ["#182B49", "#C69214", "#FFFFFF"], prestigeBase: 57 },
	{ fullName: "University of California, Santa Barbara", city: "Santa Barbara", mascot: "Gauchos", state: "CA", conference: "Big West", colors: ["#003660", "#FEBC11", "#FFFFFF"], prestigeBase: 61 },

	// America East Conference (9 teams)
	{ fullName: "University at Albany, SUNY", city: "Albany", mascot: "Great Danes", state: "NY", conference: "America East", colors: ["#461660", "#EEB211", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Binghamton University", city: "Binghamton", mascot: "Bearcats", state: "NY", conference: "America East", colors: ["#005A43", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "Bryant University", city: "Smithfield", mascot: "Bulldogs", state: "RI", conference: "America East", colors: ["#000000", "#C8B581", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "University of Maine", city: "Orono", mascot: "Black Bears", state: "ME", conference: "America East", colors: ["#003263", "#8A8D8F", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "University of Maryland, Baltimore County", city: "Baltimore", mascot: "Retrievers", state: "MD", conference: "America East", colors: ["#000000", "#FFC20E", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "University of Massachusetts Lowell", city: "Lowell", mascot: "River Hawks", state: "MA", conference: "America East", colors: ["#004165", "#FFFFFF", "#000000"], prestigeBase: 55 },
	{ fullName: "University of New Hampshire", city: "Durham", mascot: "Wildcats", state: "NH", conference: "America East", colors: ["#003466", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "New Jersey Institute of Technology", city: "Newark", mascot: "Highlanders", state: "NJ", conference: "America East", colors: ["#C8102E", "#003087", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "University of Vermont", city: "Burlington", mascot: "Catamounts", state: "VT", conference: "America East", colors: ["#00643D", "#D4AF37", "#FFFFFF"], prestigeBase: 60 },

	// ASUN Conference (12 teams)
	{ fullName: "Austin Peay State University", city: "Clarksville", mascot: "Governors", state: "TN", conference: "ASUN", colors: ["#C8102E", "#000000", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Bellarmine University", city: "Louisville", mascot: "Knights", state: "KY", conference: "ASUN", colors: ["#BA0C2F", "#FFFFFF", "#000000"], prestigeBase: 56 },
	{ fullName: "University of Central Arkansas", city: "Conway", mascot: "Bears", state: "AR", conference: "ASUN", colors: ["#592C82", "#8A8D8F", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Eastern Kentucky University", city: "Richmond", mascot: "Colonels", state: "KY", conference: "ASUN", colors: ["#6C2E40", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "Florida Gulf Coast University", city: "Fort Myers", mascot: "Eagles", state: "FL", conference: "ASUN", colors: ["#003366", "#007749", "#FFFFFF"], prestigeBase: 63 },
	{ fullName: "Jacksonville University", city: "Jacksonville", mascot: "Dolphins", state: "FL", conference: "ASUN", colors: ["#046A38", "#CCCCCC", "#FFFFFF"], prestigeBase: 56 },
	{ fullName: "Lipscomb University", city: "Nashville", mascot: "Bisons", state: "TN", conference: "ASUN", colors: ["#582C83", "#C5B358", "#FFFFFF"], prestigeBase: 59 },
	{ fullName: "University of North Alabama", city: "Florence", mascot: "Lions", state: "AL", conference: "ASUN", colors: ["#461660", "#CFAB7A", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "University of North Florida", city: "Jacksonville", mascot: "Ospreys", state: "FL", conference: "ASUN", colors: ["#003366", "#909090", "#FFFFFF"], prestigeBase: 58 },
	{ fullName: "Queens University of Charlotte", city: "Charlotte", mascot: "Royals", state: "NC", conference: "ASUN", colors: ["#003263", "#FFD100", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "Stetson University", city: "DeLand", mascot: "Hatters", state: "FL", conference: "ASUN", colors: ["#046A38", "#FFFFFF", "#000000"], prestigeBase: 57 },
	{ fullName: "University of West Georgia", city: "Carrollton", mascot: "Wolves", state: "GA", conference: "ASUN", colors: ["#003087", "#C8102E", "#FFFFFF"], prestigeBase: 52 },

	// NEC (10 teams)
	{ fullName: "Central Connecticut State University", city: "New Britain", mascot: "Blue Devils", state: "CT", conference: "NEC", colors: ["#003087", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "Chicago State University", city: "Chicago", mascot: "Cougars", state: "IL", conference: "NEC", colors: ["#00563F", "#FFFFFF", "#000000"], prestigeBase: 48 },
	{ fullName: "Fairleigh Dickinson University", city: "Teaneck", mascot: "Knights", state: "NJ", conference: "NEC", colors: ["#003087", "#8B0015", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Le Moyne College", city: "Syracuse", mascot: "Dolphins", state: "NY", conference: "NEC", colors: ["#00703C", "#CFAB7A", "#FFFFFF"], prestigeBase: 54 },
	{ fullName: "Long Island University", city: "Brooklyn", mascot: "Sharks", state: "NY", conference: "NEC", colors: ["#003478", "#C5B358", "#FFFFFF"], prestigeBase: 55 },
	{ fullName: "Mercyhurst University", city: "Erie", mascot: "Lakers", state: "PA", conference: "NEC", colors: ["#00563F", "#FFC600", "#FFFFFF"], prestigeBase: 53 },
	{ fullName: "University of New Haven", city: "West Haven", mascot: "Chargers", state: "CT", conference: "NEC", colors: ["#C5993E", "#002D62", "#FFFFFF"], prestigeBase: 52 },
	{ fullName: "Saint Francis University", city: "Loretto", mascot: "Red Flash", state: "PA", conference: "NEC", colors: ["#BA0C2F", "#FFFFFF", "#000000"], prestigeBase: 54 },
	{ fullName: "Stonehill College", city: "Easton", mascot: "Skyhawks", state: "MA", conference: "NEC", colors: ["#502D8C", "#FFFFFF", "#000000"], prestigeBase: 53 },
	{ fullName: "Wagner College", city: "Staten Island", mascot: "Seahawks", state: "NY", conference: "NEC", colors: ["#00563F", "#FFFFFF", "#000000"], prestigeBase: 54 },

	// Mountain West - Grand Canyon (1 team)
	{ fullName: "Grand Canyon University", city: "Phoenix", mascot: "Antelopes", state: "AZ", conference: "Mountain West", colors: ["#522D80", "#FFFFFF", "#000000"], prestigeBase: 61 },
];
